/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/': RouteRecordInfo<
      '/aplikasi/',
      '/aplikasi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/approval/': RouteRecordInfo<
      '/aplikasi/approval/',
      '/aplikasi/approval',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/approval/[id]': RouteRecordInfo<
      '/aplikasi/approval/[id]',
      '/aplikasi/approval/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/aplikasi/visit/': RouteRecordInfo<
      '/aplikasi/visit/',
      '/aplikasi/visit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/visit/mcl/': RouteRecordInfo<
      '/aplikasi/visit/mcl/',
      '/aplikasi/visit/mcl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/visit/mcl/[id]': RouteRecordInfo<
      '/aplikasi/visit/mcl/[id]',
      '/aplikasi/visit/mcl/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/aplikasi/visit/mcl/add-mcl': RouteRecordInfo<
      '/aplikasi/visit/mcl/add-mcl',
      '/aplikasi/visit/mcl/add-mcl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/visit/rencana': RouteRecordInfo<
      '/aplikasi/visit/rencana',
      '/aplikasi/visit/rencana',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aplikasi/visit/rencana-mingguan': RouteRecordInfo<
      '/aplikasi/visit/rencana-mingguan',
      '/aplikasi/visit/rencana-mingguan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/product': RouteRecordInfo<
      '/product',
      '/product',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RegisterView': RouteRecordInfo<
      '/RegisterView',
      '/RegisterView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/report-view': RouteRecordInfo<
      '/report-view',
      '/report-view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/index.vue': {
      routes:
        | '/aplikasi/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/approval/index.vue': {
      routes:
        | '/aplikasi/approval/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/approval/[id].vue': {
      routes:
        | '/aplikasi/approval/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/aplikasi/visit/index.vue': {
      routes:
        | '/aplikasi/visit/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/visit/mcl/index.vue': {
      routes:
        | '/aplikasi/visit/mcl/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/visit/mcl/[id].vue': {
      routes:
        | '/aplikasi/visit/mcl/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/aplikasi/visit/mcl/add-mcl.vue': {
      routes:
        | '/aplikasi/visit/mcl/add-mcl'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/visit/rencana.vue': {
      routes:
        | '/aplikasi/visit/rencana'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/aplikasi/visit/rencana-mingguan.vue': {
      routes:
        | '/aplikasi/visit/rencana-mingguan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/product.vue': {
      routes:
        | '/product'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/RegisterView.vue': {
      routes:
        | '/RegisterView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/report-view.vue': {
      routes:
        | '/report-view'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
